### ISSUE TITLE
cr_journals() - details on output

### ISSUE THREAD

**Issue by SteveViss** [ropensci/rcrossref#105]
Hi @sckott,

With @KevCaz, we are wondering:
1. What backfile.dois (chr) and current.dois (chr) mean in `cr_journals()` function output ? 
2. Do you have any idea how the score value is computed in the crossref API and what is a good `score` ?

Thanks for your time,
Steve

**Comment by sckott** [comment]
Hi @SteveViss - thanks for your questions

> What backfile.dois (chr) and current.dois (chr) mean in cr_journals() function output ? 

See this issue https://github.com/CrossRef/rest-api-doc/issues/47#issuecomment-73571019 - basically:

_current records are anything published in the last two years. Back file records have a publication date older than two years ago._

> Do you have any idea how the score value is computed in the crossref API and what is a good score ?

I know it is a relevance score, but not sure how it's computed - I imagine by their Solr engine - @kjw @afandian ?

**Comment by SteveViss** [comment]
Thanks @sckott. I'm opening a new issue on the rest-api-doc repo to get the answer on the score. You can close this one.

**Comment by sckott** [comment]
i'll leave open until we get an answer - i may need to update docs here, etc.

**Comment by SteveViss** [comment]
See this issue for the question 2  [CrossRef/rest-api-doc#116](https://github.com/CrossRef/rest-api-doc/issues/116)
I let you know if I have any update.
