### ISSUE TITLE
cr_ft_links output NULL, even if a PDF exists and DOI leads directly to it

### ISSUE THREAD

**Issue by finsoc** [ropensci/rcrossref#107]
Hi! I'm trying a quick test 

```r
cr_works(query="systemic risk",filter=list(has_full_text = TRUE))
$meta
  total_results  search_terms start_index items_per_page
1        224900 systemic risk           0             20

$data
Source: local data frame [20 x 32]

   alternative.id                                                 container.title    created  deposited
            (chr)                                                           (chr)      (chr)      (chr)
1                 Bubble Value at Risk,A Countercyclical Risk Management Approach 2015-09-26 2015-09-26
2                       Peterson/Investment,Investment Theory and Risk Management 2015-09-19 2015-09-19
... cutoff
```

However, none of the first 20 results can give me a link:

```r
FullTextWorks <- cr_works(query="systemic risk",filter=list(has_full_text = TRUE))
FullTextDois <- FullTextWorks$data$DOI
links <- cr_ft_links(FullTextDois[3])
```
links is NULL.
While the DOI in this specific example - http://dx.doi.org/10.1111/j.1468-036x.2010.00603.x - leads to Wiley Online Library.
If I could generate the links to full text, then (given the fact that my institution has subscribes to Wiley, and I can get credentials to pass paywall) I would be able to do an automated download of multiple papers for text mining. Is there another way to get links? Or why is cr_ft_links failing?

Apart from Wiley I have tried a paper published by NBER; where a DOI (http://dx.doi.org/10.3386/w17454), directly leads to a PDF (no paywall in between). Still, `cr_ft_links("10.3386/w17454")` or `cr_ft_links(doi = "10.3386/w17454", "pdf")` return NULL.

Have I missed something? 
Thank you!

**Comment by sckott** [comment]
thanks for your question:

* For your search eg with many DOIs, Wiley doesn't have their content-type's correct, they almost always say `unspecified`, even though they only provide PDF links. So just use `type="all"` to get any links they provide, try:

```r
res <- cr_works(query="systemic risk",filter=list(has_full_text = TRUE))
FullTextDois <- res$data$DOI
(links <- vapply(FullTextDois, cr_ft_links, list(1), type = "all"))
```

I should probably make getting all link types the default instead of `xml` as it is now

* DOI `10.3386/w17454`: that one doesn't have a full text URL in the crossref API, see http://api.crossref.org/works/10.3386/w17454

**Comment by finsoc** [comment]
but if http://dx.doi.org/10.3386/w17454 converts to http://www.nber.org/papers/w17454.pdf in browser, is there a way to do it in R? So that I can get full text URLs even for instances where these links are missing in crossref API metadata.
Thanks again.

**Comment by sckott** [comment]
Problem is every publisher's URL's are different - hence the importance of the links provided by Crossref. 

There is the possibility of a large set of crosswalks where a DOI is given and we try to get a link to the pdf  based on the publisher - will think about this

**Comment by sckott** [comment]
closing here, moved to new repo
