### ISSUE TITLE
cr_citation_count gives number of citations in PLoS Journals only?

### ISSUE THREAD

**Issue by finsoc** [ropensci/rcrossref#108]
Another question. About **cr_citation_count**: does it return the number of times a work is cited in PLoS Journals?  
My example:
```
cr_citation_count(doi="10.3386/w17454")
[1] 8
```
When I check JSON Metadata for this paper:
https://api.crossref.org/v1/works/http://dx.doi.org/10.3386/w17454
I don't see any citation information. crossref doesn't have this type of data - so the citation count data is provided by PLoS, right?

Thank you for clarification!

**Comment by sckott** [comment]
thanks for your question. The function uses an older Crossref service http://labs.crossref.org/openurl/ - Crossref may include citation counts in their new API (used by most of the `cr_*` functions) but not yet 

curious, why did you think it was from PLOS journals?

**Comment by finsoc** [comment]
@sckott thank you for a superfast reply!

Since I didn't find citation number in crossref JSON Metadata, I went to check about the function in the documentation file on CRAN (https://cran.r-project.org/web/packages/rcrossref/rcrossref.pdf) - and there it says (p.6) 

> doi: digital object identifier for an article in PLoS Journal
So I thought maybe that's PLoS structuring all the citations and making this data accessible...
Ok, now, do I understand this correctly: the new crossref API, where metadata is delivered in JSON doesn't have citation count, but their old openurl service does? Do they still give out new API keys for openurl then? Or I won't need the key? Can I, for example, find out what those 8 cited by papers are? Thank you!

**Comment by sckott** [comment]
Woops! Sorry about that, it shouldn't say for PLOS journals, I'll fix that. 

>  the new crossref API, where metadata is delivered in JSON doesn't have citation count, but their old openurl service does?

yes

> Do they still give out new API keys for openurl then? Or I won't need the key?

you don't need one

> Can I, for example, find out what those 8 cited by papers are? 

No, that's information publishers don't want to part with, though they are sort of okay with giving away number of citations

**Comment by sckott** [comment]
@finsoc updated the docs, closing now
