### ISSUE TITLE
Finding all articles published in a given publisher

### ISSUE THREAD

**Issue by sje30** [ropensci/rcrossref#112]
Hi,

I'd like to find out details about all articles published so far on biorxiv (http://biorxiv.org).  in particular, what I'd like to do is something like:

    cr_cn(dois="10.1101/*", format="text")

so I'd like dois to be just the prefix for Biorxiv.  But that doesn't work.  Is there a way to grab all the DOIs issued by that journal?  I couldn't see any examples of searching works just by DOI prefix.

thanks, Stephen

**Comment by sckott** [comment]
yes, there is a way, just a minute

**Comment by sckott** [comment]
You can get the member id for Cold Spring Harbor Press like 

```r
cr_members(query = "cold spring harbor")$data$id
#> [1] 246
```

Can't search on biorxiv at all, but seems that biorxiv preprints are classified as `type = "report"`, rather than article or journal article, so this could work:

```r
res <- cr_prefixes(prefixes = "10.1101", works = TRUE, filter = list(type = "report"))
res$data$DOI
#>  [1] "10.1101/030973" "10.1101/030981" "10.1101/030999" "10.1101/031005" "10.1101/031047" "10.1101/031062" "10.1101/031070" "10.1101/031096"
#>  [9] "10.1101/031104" "10.1101/031138" "10.1101/031146" "10.1101/031187" "10.1101/031245" "10.1101/031252" "10.1101/000984" "10.1101/001156"
#> [17] "10.1101/007237" "10.1101/007260" "10.1101/006247" "10.1101/006809"
```

you have to page through results to get all of the results -  max `limit` param is 1000, so just use that param and `offset`

let me know if that gets what you want

**Comment by sje30** [comment]
Thanks!  This looks great.  I will investigate and report back.

**Comment by sje30** [comment]
Thanks again Scott.  I think this works fine, but is rate-limited by crossref:

```
get_chunk = function(offset=0, limit=20) {
  res <- cr_prefixes(prefixes = "10.1101", works = TRUE,
                     filter = list(type = "report"),
                     offset=offset, limit=limit)
  dois = res$data$DOI
  res = cr_works(dois=dois)
  l = data.frame(doi=dois, created=res$data$created)
  l
}


get_chunks = function(offset=0) {
  f = data.frame()
  limit = 1000
  looking = TRUE
  while (looking) {
    f2 = get_chunk(offset, limit)
    offset = offset + limit
    print(offset)
    f = rbind(f, f2)
    if (nrow(f2) < limit) {
      looking = FALSE
    }
  }
  f
}
  
f3 = get_chunks()
```

In the meantime, I have now found a page on biorxiv that I can quickly screen-scrape; not as elegant, but a lot quicker.  Will write it up.

But thanks again for your rapid help with this, I'm sure I'll be returning to this usage pattern!

**Comment by sckott** [comment]
@sje30 thanks for the example. 

for lots of results, see the `cursor` and `cursor_max` params in many of the `cr_*()` functions. There's examples in the docs for these as well, including for `cr_prefixes`

the associated crossref docs: https://github.com/CrossRef/rest-api-doc/blob/master/rest_api.md#deep-paging-with-cursors

how many are you expecting? i thought biorxiv had only about 4000 dois?

**Comment by sckott** [comment]
What do you mean by rate limiting? can you show me the error/message you got

**Comment by sje30** [comment]
Thanks Scott.

By 'rate limiting' I simply meant slow... the code takes about 20 mins to get all the DOIs (yes, about 4000 unique).  So I assumed there is some slowness implicit in grabbing a lot of data from crossref.

**Comment by sje30** [comment]
By contrast:


```
w3m -dump -cols 999  http://www.cshsymposium.com/biorxiv/show_all.php > o2.txt
```

gets me the data I need which I can then cut using:

```
dat = readLines("o2.txt")

dat = dat[-(1:6)]

## remove blank lines.
g = grep("^$", dat)
dat = dat[-g]
## find last line "Total Articles, Unique: "
g = grep("^Total Articles, Unique", dat)

## throw away tail.
dat = dat[-(g:length(dat))]

dois = substring(dat, 7, 20)
dates = as.Date(substring(dat, 28, 37))
hist(dates, "months", format="%d-%b-%y", freq=TRUE)
```

to get me what I'm after (for now) for a talk.

**Comment by sckott** [comment]
So the extra call you made to `cr_works` isn't necessary, as the call to `cr_prefixes()` with `works=TRUE` gives the works themselves, so you can get all the data you got from `cr_works`. so 

```r
get_chunk = function(offset=0, limit=20) {
  res <- cr_prefixes(prefixes = "10.1101", works = TRUE,
                     filter = list(type = "report"),
                     offset=offset, limit=limit)
  data.frame(doi=res$data$DOI, created=res$data$created, stringsAsFactors = FALSE)
}

get_chunks = function(offset=0) {
  f = data.frame()
  limit = 1000
  looking = TRUE
  while (looking) {
    f2 = get_chunk(offset, limit)
    offset = offset + limit
    print(offset)
    f = rbind(f, f2)
    if (nrow(f2) < limit) {
      looking = FALSE
    }
  }
  f
}

system.time( (f3 = get_chunks()) )
#>   user  system elapsed 
#>  25.816   0.494  70.064 
```

only takes 70 seconds on my machine

**Comment by sckott** [comment]
and like i said you can use cursor, e.g., 

```r
system.time(
  res <- cr_prefixes(prefixes = "10.1101", works = TRUE, limit = 1000, cursor = "*", cursor_max = 5000,
                     filter = list(type = "report"), .progress = "text")
)
#>   user  system elapsed 
#>  23.098   0.336  44.790
```

takes 44 seconds on my machine

**Comment by sje30** [comment]
woah, neat!  Thank you.  It comes in about 40 seconds on my machine too.  Thank you so much.
