### ISSUE TITLE
Errors on doi with special characters 

### ISSUE THREAD

**Issue by dfalster** [ropensci/rcrossref#117]
Great package! I got an error when making the following query, which is possibly to do with the unusual characters, even though [data do exist for this item](http://search.crossref.org/?q=10.1890%2F0012-9615%281999%29069%5B0569%3AEDILSA%5D2.0.CO%3B2):

```
> cr_cn(dois = "10.1890/0012-9615(1999)069[0569:EDILSA]2.0.CO;2")
Error in if (is.na(agency_id)) { : argument is of length zero
In addition: Warning messages:
1: 404: Resource not found. - (10.1890/0012-9615(1999)069[0569:EDILSA]2.0.CO;2) 
2: In is.na(agency_id) :
  is.na() applied to non-(list or vector) of type 'NULL'
```
 
I'm documenting this bug for sake of improving the package robustness, not because I need a fix (I'll use a workaround for now).

**Comment by sckott** [comment]
thanks! will get sorted

**Comment by sckott** [comment]
@dfalster okay, reinstall and try it again
