### ISSUE TITLE
Allow to do field queries

### ISSUE THREAD

**Issue by holgerbrandl** [ropensci/rcrossref#119]
It would be awesome if rcrossref would also allow to do field queries. See https://github.com/CrossRef/rest-api-doc/blob/master/rest_api.md#field-queries

**Comment by sckott** [comment]
thanks @holgerbrandl 

there's already an open issue for this https://github.com/ropensci/rcrossref/issues/111 

if okay with you, ill close this one in favor of the previous issue

**Comment by holgerbrandl** [comment]
Oh i missed it.sorry for the tracker spam.

**Comment by sckott** [comment]
no worries, useful to know people are wanting the feature
