### ISSUE TITLE
add async in a dev branch

### ISSUE THREAD

**Issue by sckott** [ropensci/rcrossref#121]

**Comment by sckott** [comment]
new rate limit: 10/sec/IP

**Comment by sckott** [comment]
@pkraker install like `remotes::install_github("ropensci/rcrossref@async")`

try 

```r
queries <- c("ecology", "science", "cellular", "birds", "European",
   "bears", "beets", "laughter", "hapiness", "funding")
system.time(cr_works(query = c(queries, queries), async = TRUE))
#>   user  system elapsed
#>  1.183   0.077   3.552
system.time(lapply(c(queries, queries), function(z) cr_works(query = z)))
#>   user  system elapsed
#>  1.376   0.047  16.435
```

**Comment by pkraker** [comment]
Thanks! Unfortunately, I get the following error:

```
> system.time(cr_works(query = c(queries, queries), async = TRUE))
Error in FUN(X[[i]], ...) : object 'HttpRequest' not found
Timing stopped at: 0 0 0
```

**Comment by sckott** [comment]
@pkraker okay, try again, instructions updated above (i.e., recycle page)

**Comment by pkraker** [comment]
Thanks, works great now. In my case, it was 3-times faster (train wifi though, which does not provide the most reliable test setup ;)):

```
> system.time(lapply(c(queries, queries), function(z) cr_works(query = z)))
   user  system elapsed 
   1.39    0.14   22.86 
```

```
> system.time(cr_works(query = c(queries, queries), async = TRUE))
   user  system elapsed 
   0.99    0.02    7.08 
```

Also pinging @chreman

**Comment by chreman** [comment]
I can contribute a certainly reliable test setup via mobile phone roaming hotspot ;) with an observed speedup of ~2.5

**Comment by sckott** [comment]
@chreman pushed change e2272eecf4ee28039efd312a6b7cd46b76e8875f - stop message now because no benefit to doing async when only 1 thing

**Comment by sckott** [comment]
note to self, only implemented for `cr_works` and `cr_works_`
