### ISSUE TITLE
Relationship web search - API - rcrossref

### ISSUE THREAD

**Issue by jackva** [ropensci/rcrossref#138]
Hi,

I am not strictly sure this is a bug or just a difference between web and API (or my lack of knowledge):

E.g. when I enter on the web interface this gives meaningful results on finding references that discuss emissions trading and Paris Agreement:
+"emission trading" +'Paris Agreement'

I have tried reproducing this search in rcrossref (with cr_works) but without success (e.g. " "+\"emission+trading\"+\'Paris Agreement\'" "

The results are very different.
What would be the correct syntax to pass this on / duplicate the web result or is this indeed a difference?

Thanks in advance,
Johannes

**Comment by sckott** [comment]
Thanks for opening the issue @jackva  - to be clear are you talking about the search in the box here https://www.crossref.org/

**Comment by jackva** [comment]
Yes, indeed! Thank you for the prompt reply!

**Comment by sckott** [comment]
@kjw any thoughts on this?  Does search on the crossref website use the API?  browser devtools doesn't show any crossref API URLs, but doesn't mean it isn't used under the hood.

**Comment by arw36** [comment]
We have had the same issue, with using the "+" in the main crossref search allows for Boolean search "AND", but when using for cr_works function it doesn't work instead doing the standard "OR" search. For example via search (http://search.crossref.org/)
Dominican  Republic = 119013 results
+Dominican +Republic = 2,758 results

In R using rcrossref, 
```
dr_search <- cr_works(query = "+Dominican +Republic") 
```
dr_search$meta$total_results = 119013 

Let me know if you would like clarification, thanks!

**Comment by sckott** [comment]
thanks @arw36 - sorry about the delay @jackva , didn't hear from crossref, so forgot about this. 

yes, @arw36 i can replicate what you get. 

so search.crossref.org may not use the same API `rcrossref` uses. which can lead to different results. @kjw @gbilder - What is used under the hood at search.crossref.org ?  Is the search API used directly, or some modification of it?

**Comment by kjw** [comment]
So currently search.crossref.org doesn't use the API and is probably searching on a different set of default fields. Not sure if this is good or bad, but at some point we intend to rewrite the search site to use the API. If one of the results from either search.crossref.org or the API is preferred, please let me know, I'd like to understand what results people want to see.

**Comment by sckott** [comment]
thanks @kjw  - do i have this right: search.crossref.org allows amore complicated set of queries (possibly dismax ?) while api.crossref.org allows simple queries (no dismax)

**Comment by sckott** [comment]
i think the question here is mostly answered, closing
