### ISSUE TITLE
`cr_cn`: behave better when bibentry not valid

### ISSUE THREAD

**Issue by sckott** [ropensci/rcrossref#147]
via https://twitter.com/SVissault/status/931183793909780481

probably catch warning on invalid bibentry, but still return the object (and print warning)

**Comment by sckott** [comment]
hmm, `tryCatch` isn't really working - maybe because the `read.bib` fxn internally is using tryCatch? https://github.com/romainfrancois/bibtex/blob/master/R/bibtex.R#L258-L268 

looks like `do_read_bib` would work, but not sure if that's meant for same purpose, though it is exported. e.g., 

[tmpscratch.txt](https://github.com/ropensci/rcrossref/files/1479583/tmpscratch.txt)

```r
bibtex::do_read_bib("tmpscratch.bib", srcfile = srcfile("tmpscratch.bib"))
```

cc @SteveViss

**Comment by sckott** [comment]
@SteveViss do you think that solution is a good one above?

**Comment by SteveViss** [comment]
@sckott, this is a solution. `do_read_bib` is more permissive and allows to read unvalid entries. Thanks !

**Comment by sckott** [comment]
thanks @SteveViss will make change and see how it works

**Comment by beausoleilmo** [comment]
The question is more how to make a bib format for `rcrossref::cr_cn("10.1038/46731",format="bibentry")`. Or maybe I don't understand what you mean. it seems you resolved this by doing `rcrossref::cr_cn("10.1038/46731",format="bibtex")` and running `bibtex::do_read_bib("tmpscratch.txt", srcfile = srcfile("tmpscratch.txt"))`. Right?

**Comment by sckott** [comment]
the problem is that if you request `format="bibentry"` you can sometimes get malformed bib data and then the `bibtex` package fails to parse it, so we're trying to get around that

**Comment by sckott** [comment]
sorry for long wait on this @SteveViss @beausoleilmo 

can you reinstall  `devtools::install_github("ropensci/rcrossref")` and try bibtex egs again
