### ISSUE TITLE
Add New Entry with PMID

### ISSUE THREAD

**Issue by cholyavkin** [ropensci/rcrossref#148]
Is it possible to add new citation entry by using only PMID or PMCID? Some of older articles ([example](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC387126/?page=2)) do not have a doi number. Unfortunately, the rcrossref add-in only accepts doi numbers.

How can I add the new entry to my crossref.bib with PMID?

**Comment by sckott** [comment]
thanks for the issue @cholyavkin 

There was a web service to convert between PMID and DOIs , but it no longer works. 

can look into it, but i think this pkg focuses on Crossref, so probably wouldn't introduce Pubmed tools since other R pkgs handle Entrez/Pubmed data, but will look

**Comment by cholyavkin** [comment]
Thank you for your interest @sckott .

I just noticed that Crossref can find the doi numbers, even the original journal page doesn't have any. I know that it is not easy but you may consider adding "**Search by Title**" feature to the add-in in next updates.

![ekran resmi 2017-12-19 15 44 25](https://user-images.githubusercontent.com/28393339/34157771-027c57b4-e4d4-11e7-9645-355cedbe0d68.png)

**Comment by sckott** [comment]
thanks @cholyavkin 

@haozhu233  thoughts on the above?

**Comment by sckott** [comment]
@haozhu233 any thoughts?

**Comment by haozhu233** [comment]
@sckott @cholyavkin just want to give you an update. I'm adding a general search panel to the addin using the `cr_works` function. Right now I still need some extra time to get everything in place.

**Comment by sckott** [comment]
@cholyavkin can you reinstall `remotes::install_github("ropensci/rcrossref")` and try the new version of the addin again?

**Comment by cholyavkin** [comment]
**OMG!**  It's so beautiful and works like a charm. Thank you @haozhu233 and @sckott.

![sc](https://user-images.githubusercontent.com/28393339/36665384-76481502-1af8-11e8-89a8-e2907031b5d4.png)
