### ISSUE TITLE
Buffer issues while attempting to use cr_journals()

### ISSUE THREAD

**Issue by damianooldoni** [ropensci/rcrossref#155]
I would like to use function `cr_journals()` on a vector containing a lot of issn codes (~1500) to retrieve journal titles.
First, I tried to do it by calling `cr_journals()` on the entire vector:
```r
journal_titles <- cr_journals(issn = issns)$data$title
```
It failed with the following error message:
> Error in curl::curl_fetch_memory(x$url$url, handle = x$url$handle) : 
  schannel: next InitializeSecurityContext failed: SEC_E_MESSAGE_ALTERED (0x8009030F) - Het bericht of de handtekening die zijn opgegeven voor controle zijn gewijzigd.

translating from Dutch: *"The message or the signature given for control are changed."*

I tried to do it one by one:
```r
journal_names <- NA
for (i in 1:length(issns)) {
  journal_name <- cr_journals(issn = issns[i])$data$title
  journal_names[i] <- ifelse(is.null(journal_name), NA, journal_name)
}
```
but I get at a certain point the same error message.

After few attempts I get this other error:
> Error in curl::curl_fetch_memory(x$url$url, handle = x$url$handle) : 
  schannel: next InitializeSecurityContext failed: SEC_E_BUFFER_TOO_SMALL (0x80090321) - De buffers die zijn geleverd aan een functie zijn te klein.

translating from Dutch: *"The buffers given to a function are too small."*

Any hint/suggestion/idea is very appreciated. Thanks!
<details> <summary><strong>Session Info</strong></summary>

Session info [here](https://github.com/ropensci/rcrossref/files/1816955/Session.info.txt).

**Comment by sckott** [comment]
thanks for the issue @damianooldoni 

Are you using your email address to get in to the fast lane? https://github.com/ropensci/rcrossref/blob/master/R/rcrossref-package.R#L70-L88 https://github.com/CrossRef/rest-api-doc#etiquette

**Comment by sckott** [comment]
I tried with 

```r
library(rcrossref)
z <- cr_journals(query="american", limit=1000)
issns <- Filter(Negate(is.na), z$data$issn)
length(issns)
cr_journals(issn = issns)
```

didn't raise any problems. its possible using an email address if you're not will help, but the error seems more like a curl problem, and not with crossref rate limiting you. 

does it work with a small number of issn's?  

can you pass `verbose = TRUE` in the call to see if there's some useful info in the response headers

**Comment by damianooldoni** [comment]
Thanks @sckott, 
I am now using e-mail address, sorry to not doing it since the begining. However, the problem is not solved.
By running your example, I get still the error:
 `SEC_E_MESSAGE_ALTERED (0x8009030F): The message or signature supplied for verification has been altered` 
or, alternatively: 
`SEC_E_BUFFER_TOO_SMALL (0x80090321): The buffers supplied to a function was too small`.

Sometimes I can query 150 or even 200 issn at once, sometimes the error comes up at the very beginning, sometimes much later. I didn't find a logic behind. For example, last time I tried your example, with `verbose = TRUE` I get the buffer error at the `issns[195]` and the previous time it was at ìssn[33]`. I am investigating a little more on internet and on GItHub issues page of curl package. It can be a Windows problem (firewall, antivirus, ...) I will move my question to curl if I don't find a solution.
Thanks for your help!

**Comment by sckott** [comment]
@damianooldoni any thoughts on this?

**Comment by damianooldoni** [comment]
No, @sckott, I 'm sorry. Actually the library didn't need this kind of information. So, I had to change my plans very soon. And no free time available for this. I am sorry.

**Comment by sckott** [comment]
thanks @damianooldoni

**Comment by sckott** [comment]
@jeroen have you seen these https://github.com/ropensci/rcrossref/issues/155#issue-305722632 types of errors ever (SEC_E_MESSAGE_ALTERED and SEC_E_BUFFER_TOO_SMALL)? i'm not sure what they mean

**Comment by jeroen** [comment]
No i've not seen this before. It looks like a bug in libcurl. @damianooldoni are you using the latest version of the curl package?

**Comment by sckott** [comment]
any thoughts @damianooldoni on jeroen's comment above ?

**Comment by nicholasmfraser** [comment]
I am receiving exactly the same error messages as @damianooldoni (SEC_E_MESSAGE_ALTERED and SEC_E_BUFFER_TOO_SMALL) when using function `cr_works()` to loop through a vector of ~1000 DOIs. As with @damianooldoni it is inconsistent, it sometimes fails on the first few requests, sometimes after 100+ requests.

I am on Windows 7, using latest curl package for R (3.2), and am using my email address to get in the 'fast lane'. I've tried adding firewall exceptions, adding pauses between requests (to ensure its not related to server rate limiting), using the `httr::set_config()` function following [this similar issue](https://github.com/Bioconductor/GenomicDataCommons/issues/35), upgraded and reinstalled curl/libcurl/openssl on windows, all to no avail. I have not been able to replicate the issue so far using curl on the command line. Any thoughts?

**Comment by jeroen** [comment]
This must be a bug in libcurl. Does this always happen for this specific host? @jay does this error sound familiar?

**Comment by bagder** [comment]
Never seen it before.

`SEC_E_MESSAGE_ALTERED` is wonderfully undocumented and hard to find described by Microsoft. I suppose a reason to try using another TLS backend to see if the problem persists then too.

The very name of this error does however not sound like its a libcurl error to me, its sounds like a problem with the server. But that's just a wild guess..

**Comment by nicholasmfraser** [comment]
I just looped through the same dataset several times using the `GET` method of the httr package to query the crossref API directly, and did not encounter the same issue. I haven't had this issue querying any other APIs before either. I'll try to recreate it on another machine later to see if this is specific to my current machine.

**Comment by jeroen** [comment]
It's definitely a Windows issue because it happens in the schannel back-end.

**Comment by sckott** [comment]
both `crul` and `httr` R packages use  jeroen's `curl` pkg under the hood, so I am guessing it shouldn't matter which of `crul` and `httr` we use. at least I hope.

**Comment by jay** [comment]
I only know of [one curl bug report](https://curl.haxx.se/mail/lib-2016-12/0088.html) of SEC_E_MESSAGE_ALTERED. I think it's interesting that both reporters have a failure with exactly 7 bytes received. Can you wireshark it?

Also steffengy/schannel-rs#8 may be related.

**Comment by nicholasmfraser** [comment]
I came back to this task recently and encountered the same issue again. I took a look at the issue of https://github.com/steffengy/schannel-rs/issues/8 referenced above and removed `TLS_DHE_RSA_WITH_AES_128_GCM_SHA256` and `TLS_DHE_RSA_WITH_AES_256_GCM_SHA384` from the schannel SSL cipher suites order. The bug appears to have now disappeared. I do not know why this caused an issue, but just in case anyone else is experiencing the same thing.

**Comment by sckott** [comment]
thanks @nicholasmfraser for the follow up

> removed TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 and TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 from the schannel SSL cipher suites order

this is on your machine?

**Comment by nicholasmfraser** [comment]
Yes, on my local machine (Windows 7). It must be something specific to my machine, I couldn't reproduce it on another machine that also had Windows 7.

**Comment by sckott** [comment]
Okay, thanks. Where did you find instructions on how to remove those?

**Comment by nicholasmfraser** [comment]
I used the information available here, following the same process to add cipher suites at the bottom of the page (I had to restart my computer before the changes took effect): https://docs.microsoft.com/en-us/windows/desktop/secauthn/tls-cipher-suites-in-windows-7

**Comment by sckott** [comment]
ah, thanks very much @nicholasmfraser
