### ISSUE TITLE
"filter" parameter documentation out of date

### ISSUE THREAD

**Issue by ms609** [ropensci/rcrossref#161]
The documentation for the `filter` parameter in `cr_works` and elsewhere (`cr_journals`, `cr_members`, `cr_prefixes`, `cr_funders`, and others) states "Filter options. See details.", yet the details of this function do not specify how this parameter is to be used.

`cr_licenses` hints that 

> The API route behind this function does not support filters any more, so the filter parameter has been removed. 

Has the filters parameter also been removed from the other functions? (In this case the examples may also need updating.)  Or is it documented somewhere that I've missed?

**Comment by sckott** [comment]
thanks for the report @ms609 

you're right that the docs are not great on filters. 

updated the docs, reinstall and see `?cr_works` help page, there's many usage examples in `cr_works` and there's some helper functions in `?filters` for getting filter names and more details on them

**Comment by ms609** [comment]
Great, thank you!
