### ISSUE TITLE
Maybe stop/warn with API route in addition to the message. 

### ISSUE THREAD

**Issue by sckott** [ropensci/rcrossref#163]
via #162 

so e.g., 

```
400: This route does not support query - (10.26879/775)
```

becomes

```
400: This route (/works/<doi>/) does not support query - (10.26879/775)
```

**Comment by ms609** [comment]
Including part of the API URL would definitely be a helpful addition.  Is it even possible to include the full URL (with the API key obfuscated, I suppose)?  This'd make debugging a little easier.
Could the warning also mention more explicitly that the CrossRef API is the source of the error (rather than malformed R input)?  
I didn't understand the term "route" either -- though it looks like this term perhaps originates from CrossRef?
Not sure how feasible it would be to report something like:

 > CrossRef returned Error 400: the API path (api.crossref.org/works/10.26879/775/) does not support the 'query' parameter

**Comment by sckott** [comment]
rather than print out the entire URL on each request (I try to not clutter the users console if possible), the best thing to do for debugging purposes is to use curl options. Those are passed on to internal HTTP functions via `...`. the most important being `verbose = TRUE` (try it to see what happens). That is, if a user encounters an error, then they can rerun the same thing with `verbose = TRUE` added. 

The `400` is a HTTP status code https://en.wikipedia.org/wiki/List_of_HTTP_status_codes - 400 series codes mean that the client (anyone using this package) made a mistake, while the 500 series codes mean the server (Crossref) made a mistake. 

A route is the name for the various "paths" on an API. They're usually represented with a leading forward slash like `/hello`. e.g., in the Crossref API, they have routes for `/members`, `/works`, etc. Different routes allow different parameters to be given to them

**Comment by ms609** [comment]
These are some very helpful suggestions, thank you!

**Comment by sckott** [comment]
hugh, not sure why this http://api.crossref.org/works?cursor=5 is giving/:

```r
Warning message:
500 (server error): /works - {"status":"error","message-type":"exception","message-version":"1.0.0","message":{"name":"class org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException","description":"org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http:\/\/mds10:8983\/solr\/crmds1: Unable to parse 'cursorMark' after totem: value must either be '*' or the 'nextCursorMark' returned by a previous search: asdf","message":"Error from server at http:\/\/mds10:8983\/solr\/crmds1: Unable to parse 'cursorMark' after totem: value must either be '*' or the 'nextCursorMark' returned by a previous search: asdf","stack":["org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:610)","org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:279)","org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:268)","org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:149)"," [... truncated]
```
