### ISSUE TITLE
Query by category? 

### ISSUE THREAD

**Issue by PhoebeFossil** [ropensci/rcrossref#166]
Is there a way to query by category? Doesn't seem to be in "Acceptable set of field query parameters" but is searchable on the Cross Ref web interface. I.e., I want to be able to do 

`
cr_types("journal-article", works = TRUE,  select = c('author', 'title'), flq = c(`query.category` = 'Geology'), cursor_max=1000, cursor="*")`

Thanks
Phoebe

**Comment by sckott** [comment]
thanks for your question @PhoebeFossil 

i don't believe that's allowed in the API that we use here. 

you can do a filter on `category-name` like https://api.crossref.org/types/journal-article/works?filter=category-name:Geology 

in rcrossref it's `rcrossref::cr_types("journal-article", works = TRUE, filter = c(category_name = "Geology"))`

**Comment by PhoebeFossil** [comment]
Awesome, thank you! Will try this out.
