### ISSUE TITLE
rcrossref returns just one license for a work 

### ISSUE THREAD

**Issue by patrickda** [ropensci/rcrossref#170]
works can have more than one license e.g.
http://api.crossref.org/v1/works/10.1016/j.molp.2016.08.010
rcrossref only returns the first one when using

cr_works(dois ="10.1016/j.molp.2016.08.010")

<details> <summary><strong>Session Info</strong></summary>
Session info ---------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.453)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Europe/Vienna               
 date     2018-08-06                  

Packages -------------------------------------------------------------------------------------------------------------
 package     * version    date       source                             
 assertthat    0.2.0      2017-04-11 CRAN (R 3.4.0)                     
 base        * 3.4.3      2017-12-07 local                              
 bibtex        0.4.2      2017-06-30 CRAN (R 3.4.1)                     
 bindr         0.1.1      2018-03-13 CRAN (R 3.4.4)                     
 bindrcpp    * 0.2.2      2018-03-29 CRAN (R 3.4.4)                     
 broom         0.4.4      2018-03-29 CRAN (R 3.4.4)                     
 cellranger    1.1.0      2016-07-27 CRAN (R 3.4.0)                     
 cli           1.0.0      2017-11-05 CRAN (R 3.4.2)                     
 colorspace    1.3-2      2016-12-14 CRAN (R 3.4.0)                     
 compiler      3.4.3      2017-12-07 local                              
 crayon        1.3.4      2017-09-16 CRAN (R 3.4.1)                     
 crul          0.5.2      2018-02-24 CRAN (R 3.4.3)                     
 curl          3.2        2018-03-28 CRAN (R 3.4.4)                     
 datasets    * 3.4.3      2017-12-07 local                              
 devtools      1.13.6     2018-06-27 cran (@1.13.6)                     
 digest        0.6.15     2018-01-28 CRAN (R 3.4.3)                     
 dplyr       * 0.7.6      2018-06-29 cran (@0.7.6)                      
 DT            0.4        2018-01-30 CRAN (R 3.4.3)                     
 forcats     * 0.3.0      2018-02-19 CRAN (R 3.4.3)                     
 foreign       0.8-70     2018-04-23 CRAN (R 3.4.3)                     
 ggplot2     * 2.2.1      2016-12-30 CRAN (R 3.4.0)                     
 glue          1.3.0      2018-07-17 cran (@1.3.0)                      
 graphics    * 3.4.3      2017-12-07 local                              
 grDevices   * 3.4.3      2017-12-07 local                              
 grid          3.4.3      2017-12-07 local                              
 gtable        0.2.0      2016-02-26 CRAN (R 3.4.0)                     
 haven         1.1.1      2018-01-18 CRAN (R 3.4.3)                     
 hms           0.4.2      2018-03-10 CRAN (R 3.4.4)                     
 htmltools     0.3.6      2017-04-28 CRAN (R 3.4.0)                     
 htmlwidgets   1.2        2018-04-19 CRAN (R 3.4.4)                     
 httpuv        1.4.4.1    2018-06-18 CRAN (R 3.4.3)                     
 httr          1.3.1      2017-08-20 CRAN (R 3.4.1)                     
 jsonlite      1.5        2017-06-01 CRAN (R 3.4.0)                     
 later         0.7.3      2018-06-08 CRAN (R 3.4.3)                     
 lattice       0.20-35    2017-03-25 CRAN (R 3.4.3)                     
 lazyeval      0.2.1      2017-10-29 CRAN (R 3.4.2)                     
 lubridate     1.7.4      2018-04-11 CRAN (R 3.4.4)                     
 magrittr      1.5        2014-11-22 CRAN (R 3.4.0)                     
 memoise       1.1.0      2017-04-21 CRAN (R 3.4.0)                     
 methods     * 3.4.3      2017-12-07 local                              
 mime          0.5        2016-07-07 CRAN (R 3.4.0)                     
 miniUI        0.1.1.1    2018-05-18 CRAN (R 3.4.3)                     
 mnormt        1.5-5      2016-10-15 CRAN (R 3.4.0)                     
 modelr        0.1.2      2018-05-11 CRAN (R 3.4.3)                     
 munsell       0.5.0      2018-06-12 CRAN (R 3.4.3)                     
 nlme          3.1-137    2018-04-07 CRAN (R 3.4.4)                     
 parallel      3.4.3      2017-12-07 local                              
 pillar        1.2.3      2018-05-25 CRAN (R 3.4.4)                     
 pkgconfig     2.0.1      2017-03-21 CRAN (R 3.4.0)                     
 plyr          1.8.4      2016-06-08 CRAN (R 3.4.0)                     
 promises      1.0.1      2018-04-13 CRAN (R 3.4.4)                     
 psych         1.8.4      2018-05-06 CRAN (R 3.4.3)                     
 purrr       * 0.2.5      2018-05-29 CRAN (R 3.4.4)                     
 R6            2.2.2      2017-06-17 CRAN (R 3.4.0)                     
 Rcpp          0.12.18    2018-07-23 cran (@0.12.18)                    
 rcrossref   * 0.8.1.9513 2018-05-28 Github (ropensci/rcrossref@d78684a)
 readr       * 1.1.1      2017-05-16 CRAN (R 3.4.0)                     
 readxl        1.1.0      2018-04-20 CRAN (R 3.4.4)                     
 reshape2      1.4.3      2017-12-11 CRAN (R 3.4.3)                     
 rlang         0.2.1      2018-05-30 cran (@0.2.1)                      
 roadoi      * 0.5.1      2018-05-21 CRAN (R 3.4.4)                     
 rstudioapi    0.7        2017-09-07 CRAN (R 3.4.1)                     
 rvest         0.3.2      2016-06-17 CRAN (R 3.4.0)                     
 scales        0.5.0      2017-08-24 CRAN (R 3.4.1)                     
 shiny         1.1.0      2018-05-17 CRAN (R 3.4.3)                     
 stats       * 3.4.3      2017-12-07 local                              
 stringi       1.2.3      2018-06-12 CRAN (R 3.4.3)                     
 stringr     * 1.3.1      2018-05-10 CRAN (R 3.4.3)                     
 tibble      * 1.4.2      2018-01-22 CRAN (R 3.4.3)                     
 tidyr       * 0.8.1      2018-05-18 CRAN (R 3.4.3)                     
 tidyselect    0.2.4      2018-02-26 CRAN (R 3.4.3)                     
 tidyverse   * 1.2.1      2017-11-14 CRAN (R 3.4.2)                     
 tools         3.4.3      2017-12-07 local                              
 triebeard     0.3.0      2016-08-04 CRAN (R 3.4.0)                     
 urltools      1.7.0      2018-01-20 CRAN (R 3.4.3)                     
 utf8          1.1.4      2018-05-24 CRAN (R 3.4.3)                     
 utils       * 3.4.3      2017-12-07 local                              
 withr         2.1.2      2018-03-15 CRAN (R 3.4.4)                     
 XML         * 3.98-1.11  2018-04-16 CRAN (R 3.4.4)                     
 xml2          1.2.0      2018-01-24 CRAN (R 3.4.3)                     
 xtable        1.8-2      2016-02-05 CRAN (R 3.4.0)                     
 yaml          2.1.19     2018-05-01 CRAN (R 3.4.3)      
```r

```
</details>

**Comment by sckott** [comment]
thanks for the report @patrickda - having a look at this

**Comment by sckott** [comment]
should be fixed. try again after reinstalling

**Comment by patrickda** [comment]
Not it is a list with the Creative Commons license but the other one is mssing

**Comment by sckott** [comment]
@patrickda not sure i understand your last comment?

**Comment by patrickda** [comment]
@sckott 

doi = "10.1016/j.molp.2016.08.010"
CrossRef.data = cr_works(dois = doi) %>% .$data
pub.licence= CrossRef.data$license

pub.license ist a "List of 1" but it should be a "List of 2"
Shouldn't it?

**Comment by patrickda** [comment]
Sorry I overlooked that in the list is a tibble with the two licenses (still struggling a bit with nesting but I get better) ;-)
