### ISSUE TITLE
Add ".progress" option for deep pagination

### ISSUE THREAD

**Issue by Bubblbu** [ropensci/rcrossref#186]
I was wondering if it would be possible to add the option to display the plyr progress bar for deep pagination with the `cursor="*"` option. Currently, to my understanding, only lists of identifiers are supported.

**Comment by sckott** [comment]
thanks, i'll take a look.

**Comment by sckott** [comment]
@Bubblbu okay, made a change, try 

```r
remotes::install_github("ropensci/rcrossref@cursor-progress")
library(rcrossref)
cr_works(query="NSF", cursor = "*", cursor_max = 120, limit = 30, .progress = TRUE)
```

**Comment by Bubblbu** [comment]
works like a charm. awesome!

thanks!

**Comment by sckott** [comment]
great, glad it works
