### ISSUE TITLE
Help: Need to get details of all the dois citing a particular DOI 

### ISSUE THREAD

**Issue by shaniAmare** [ropensci/rcrossref#204]
HI to the developers rcrossref (@sckott, @ropenscibot),

Thank you for this wonderful package!

I was wondering whether there has been any progress with identifying the other publication details citing a DOI? I see some information here saying that it is not implemented in rcrossref : https://ciakovx.github.io/rcrossref.html. 

If this is the case, can an expert guide me on an alternative way to do it through R please? Your ideas are really appreciated!

Thanks in advance
Shani.

**Comment by sckott** [comment]
thanks for opening an issue @shaniAmare 

please be more specific. what does this mean: "identifying the other publication details citing a DOI" - what are "other publication details"

**Comment by shaniAmare** [comment]
Thanks for the reply @sckott ... and sorry for the confusion!

By other publication details, I mean particularly the dois of the articles that cite a particular article - similar to the results we see when we click on "_Cited by_" in `Google Scholar` . 

Is there a way to get this within R somehow? I think if it is achievable, `rcrossref` might be the only package that can make it happen. Another R package dealing with google scholar, (i.e. `scholar` package), could only look at scholar profiles and that scholars' citation history.

**Comment by sckott** [comment]
You can try `cr_citation_count` function  to get count of citations, but you can't get the citations themselves from Crossref. 

As mentioned in that tutorial you linked to, you can try the https://github.com/ropenscilabs/citecorp citecorp pkg, a client for the open citation corpus.

**Comment by shaniAmare** [comment]
Thanks! I will check `citecorp` out! It would have been nice if there was a function similar to `cr_citation_count` to get the dois of those counts (i.e. `cr_citation_data`) through `rcrossref`. But looking at your code, I understand that, this is not trivial...

Thanks for all the help, Scott!

Cheers,
Shani.

**Comment by sckott** [comment]
> it would have been nice if there was a function similar to cr_citation_count to get the dois of those counts

I IS NOT POSSIBLE. The data is not made available

**Comment by shaniAmare** [comment]
Noted- thanks!

**Comment by byzheng** [comment]
Could we revisit this feature request? I noticed the API in crossref for cited-by (https://www.crossref.org/documentation/cited-by/retrieve-citations/). Not sure whether it is possible to implement.

**Comment by sckott** [comment]
i no longer maintain this pkg, you can ask @njahn82 though

**Comment by njahn82** [comment]
Hi @byzheng This service is only for Crossref members, which are publishers. The freely available REST API wrapped by this package lets you only retrieve references.

**Comment by byzheng** [comment]
Thanks @sckott and @njahn82 for your comments. I find an alternative solutions for citations opencitations (https://opencitations.net/)
