### ISSUE TITLE
rCrossRef 

### ISSUE THREAD

**Issue by shashigaonkar** [ropensci/rcrossref#228]
I am new to both R and GitHub. I am trying to use rCrossRef. I have registered my email in the Polite Pool using the codes below:      
usethis :: edit_r_environ()                  followed by ,
crossref_email = example@mail.com

When I try to use rCrossRef to look up for journal details the error message pops up in R. 

 Error in cr_GET(endpoint = path, args, todf = FALSE, parse = TRUE, ...) : 
  res$response_headers$`content-type` == "application/json;charset=UTF-8" is not TRUE

I did go through the issue discussed here, and then used, 
 remote : : install_github("ropensci/rcrossref")   

But it is not working well for me. The same error message pops up.  Could anyone please help me to solve my issue?

**Comment by TobiasPolak** [comment]
I am having the same issue. It used to work perfectly well for me. Any ideas?

**Comment by njahn82** [comment]
The latest CRAN release fixes this issue.
