### ISSUE TITLE
Error or warn when NA or NULL is used as input

### ISSUE THREAD

**Issue by njahn82** [ropensci/rcrossref#53]
The CrossRef API returns valid json-output for the queries

http://api.crossref.org/works/NULL/
http://api.crossref.org/works/NA/
 
which is a very confusing behavior.  Functions should better fail or warn when  `NULL` objects or `NA` values are inputted. I can work on the issue, if needed.

**Comment by sckott** [comment]
@njahn82 That'd be great if you could do that - in addition, they return data for ISSN's that don't exist, which I've brought up with them https://github.com/CrossRef/rest-api-doc/issues/37

**Comment by njahn82** [comment]
Ok @sckott, will try to control inputs in the next days

**Comment by sckott** [comment]
thanks :+1:
