### ISSUE TITLE
Let `cr_cn` check supported content types for each doi minting agency

### ISSUE THREAD

**Issue by njahn82** [ropensci/rcrossref#88]
Aim is that `cr_cn` only allows content types as argument, which are supported by the respective agency. According to http://www.crosscite.org/cn/ supported content types differ.

I am happy to help.

**Comment by sckott** [comment]
Thanks, if you have time

**Comment by sckott** [comment]
@njahn82 you plan to do this ?

**Comment by njahn82** [comment]
Yes. However, I will start in the next week because I am currently moving. Hope, it is not problem for you.

**Comment by sckott** [comment]
no rush, it had just been a month, so I thought I'd ask

**Comment by sckott** [comment]
closed via #94
