### ISSUE TITLE
Error handling on cr_journals with iSSN / Not found message from the api 

### ISSUE THREAD

**Issue by nkorf** [ropensci/rcrossref#97]
Hi, 
First of all great thanks for this amazing package. 
I am having a problem with the cr_journals function call with an issn argument. I suspect this has to do with the crossref api not returning any details for a particular issn. If you try to run 
the function : 
`cr_journals("0413-6597")`
will return an error message as follows: 

```
Error in x$flags : $ operator is invalid for atomic vectors
In addition: Warning message:
404: Resource not found. 

```

I suspect it has to do with error handling for a 404 responce, is there a way to circumvent this issue ?

**Comment by sckott** [comment]
Thanks for the report !  That function and others loop internally so users can pass in many DOIs/ISSNs/etc. - on failure for any one we just throw a warning, but don't stop the function progress - this particular bug we didn't catch appropriately, looking at it now

**Comment by sckott** [comment]
@nkorf okay, try your eg again after reinstalling `devtools::install_github("ropensci/rcrossref")`

**Comment by nkorf** [comment]
@sckott Ok it works now. I also used a temporary workaround for the older version to surround the function call with try(). Keep up the great work.

**Comment by sckott** [comment]
great, glad it works now. 

> Keep up the great work.

will do, and keep reporting problems
