### ISSUE TITLE
search.labs.crossref.org/dois used by cr_search() down 

### ISSUE THREAD

**Issue by sckott** [ropensci/rcrossref#99]
Karl says search.crossref.org/dois should work but it gives `Internal server error`

**Comment by sckott** [comment]
`cr_search_free()` is also down due to http://search.crossref.org/links 505ing

**Comment by sckott** [comment]
was a false alarm, forgotten that the base url 500's

also, a change in `httr` meant that some queries didn't work anymore, so tweaked internal parsing of query apram

**Comment by kjw** [comment]
Will eventually take down the API features at search.crossref.org for good (probably when we merge our search UI codebase with DataCite's fork.) Alternatives:

/links -> POST http://api.crossref.org/reverse where body is a citation

Except it doesn't do batch. One at a time.

/dois?q=test -> http://api.crossref.org/works?query=test

**Comment by sckott** [comment]
thanks for commenting here

Right, I've marked the functions for the old `search.crossref.org` as deprecated, and will remove those soon. 

I didn't know about http://api.crossref.org/reverse - is that documented anywhere?
